apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-secrets-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-secrets-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aws-secrets-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
