{{- if not .Values.aws.irsaRoleArn }}
{{- if or .Values.awsCredentials.accessKeyId .Values.awsCredentials.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-secrets-app.fullname" . }}-aws-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-secrets-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | quote }}
  {{- if .Values.awsCredentials.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.awsCredentials.sessionToken | quote }}
  {{- end }}
{{- end }}
{{- end }}
