#!/bin/bash
set -e

# Deploy Infrastructure - Build and deploy SAM template to Floci
# This script builds the SAM template and deploys it to the Floci CloudFormation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging functions
log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
  exit 1
}

log_warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_header() {
  echo ""
  echo -e "${BLUE}========================================${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}========================================${NC}"
  echo ""
}

# Configuration
FLOCI_ENDPOINT="http://localhost:4566"
STACK_NAME="event-booking-platform"
REGION="us-east-1"
ENVIRONMENT="local"

# Main execution
log_header "INFRASTRUCTURE DEPLOYMENT"

# Verify Floci is running (with retries)
log_info "Verifying Floci is running..."
HEALTH_ATTEMPTS=0
MAX_HEALTH_ATTEMPTS=30
while [ $HEALTH_ATTEMPTS -lt $MAX_HEALTH_ATTEMPTS ]; do
  if curl -s "$FLOCI_ENDPOINT/_localstack/health" 2>/dev/null | grep -q -E '"state"|running|ready|services'; then
    log_info "✓ Floci is running"
    sleep 5
    break
  fi
  HEALTH_ATTEMPTS=$((HEALTH_ATTEMPTS + 1))
  if [ $HEALTH_ATTEMPTS -ge $MAX_HEALTH_ATTEMPTS ]; then
    log_error "Floci is not running. Start it with: bash scripts/setup-floci.sh"
  fi
  sleep 1
done

# Set AWS credentials
export AWS_ENDPOINT_URL=$FLOCI_ENDPOINT
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=$REGION

log_info "✓ AWS credentials configured for Floci"

# Navigate to backend
cd "$PROJECT_ROOT/backend"
log_info "Working directory: $(pwd)"

# Build SAM project
log_info "Building SAM project..."
if sam build --use-container 2>/dev/null; then
  log_info "✓ SAM built with container support"
elif sam build 2>&1; then
  log_info "✓ SAM built without container"
else
  log_error "SAM build failed. Check error output above."
fi

# Deploy SAM stack
log_info "Deploying CloudFormation stack to Floci..."
log_info "Stack name: $STACK_NAME"
log_info "Region: $REGION"

sam deploy \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --parameter-overrides Environment=$ENVIRONMENT \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --no-fail-on-empty-changeset \
  --endpoint-url "$FLOCI_ENDPOINT" || log_error "SAM deployment failed"

log_info "✓ Stack deployed successfully"

# Extract stack outputs
log_info "Extracting stack outputs..."
OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --endpoint-url "$FLOCI_ENDPOINT" \
  --query "Stacks[0].Outputs" 2>/dev/null || echo "[]")

# Save outputs to file for other scripts
ENV_FILE="$PROJECT_ROOT/.env.floci"
log_info "Saving outputs to $ENV_FILE..."

# Parse and save outputs
USER_POOL_ID=$(echo "$OUTPUTS" | grep -o '"OutputKey":"UserPoolId".*"OutputValue":"[^"]*"' | grep -o '"OutputValue":"[^"]*"' | head -1 | cut -d'"' -f4)
CLIENT_ID=$(echo "$OUTPUTS" | grep -o '"OutputKey":"UserPoolClientId".*"OutputValue":"[^"]*"' | grep -o '"OutputValue":"[^"]*"' | head -1 | cut -d'"' -f4)
API_ENDPOINT=$(echo "$OUTPUTS" | grep -o '"OutputKey":"ApiEndpoint".*"OutputValue":"[^"]*"' | grep -o '"OutputValue":"[^"]*"' | head -1 | cut -d'"' -f4)
FRONTEND_BUCKET=$(echo "$OUTPUTS" | grep -o '"OutputKey":"FrontendBucketName".*"OutputValue":"[^"]*"' | grep -o '"OutputValue":"[^"]*"' | head -1 | cut -d'"' -f4)
BOOKINGS_TABLE=$(echo "$OUTPUTS" | grep -o '"OutputKey":"BookingsTableName".*"OutputValue":"[^"]*"' | grep -o '"OutputValue":"[^"]*"' | head -1 | cut -d'"' -f4)

# Write outputs to environment file
cat > "$ENV_FILE" << EOF
# Floci Stack Outputs
# Auto-generated by deploy-infrastructure.sh

export FLOCI_ENDPOINT=$FLOCI_ENDPOINT
export STACK_NAME=$STACK_NAME
export REGION=$REGION

export USER_POOL_ID=$USER_POOL_ID
export CLIENT_ID=$CLIENT_ID
export API_ENDPOINT=$API_ENDPOINT
export FRONTEND_BUCKET=$FRONTEND_BUCKET
export BOOKINGS_TABLE=$BOOKINGS_TABLE

# For React
export REACT_APP_COGNITO_USER_POOL_ID=$USER_POOL_ID
export REACT_APP_COGNITO_CLIENT_ID=$CLIENT_ID
export REACT_APP_API_ENDPOINT=$API_ENDPOINT
export REACT_APP_COGNITO_REGION=$REGION
export REACT_APP_DEBUG=false
EOF

log_info "✓ Outputs saved to .env.floci"

# Display outputs
log_header "STACK OUTPUTS"

echo "User Pool ID:        $USER_POOL_ID"
echo "Client ID:           $CLIENT_ID"
echo "API Endpoint:        $API_ENDPOINT"
echo "Frontend Bucket:     $FRONTEND_BUCKET"
echo "Bookings Table:      $BOOKINGS_TABLE"
echo ""

# List all resources
log_info "Listing all stack resources..."
aws cloudformation list-stack-resources \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --endpoint-url "$FLOCI_ENDPOINT" \
  --query "StackResourceSummaries[*].[LogicalResourceId,ResourceType,ResourceStatus]" \
  --output table

# Next steps
log_header "DEPLOYMENT COMPLETE"

echo "Infrastructure deployed successfully!"
echo ""
echo "Next steps:"
echo "  1. Seed data:           bash scripts/seed-data.sh"
echo "  2. Build frontend:      bash scripts/build-frontend.sh"
echo "  3. Deploy frontend:     bash scripts/deploy-frontend.sh"
echo "  4. Start frontend:      bash scripts/start-frontend.sh"
echo ""
echo "Or run full pipeline:"
echo "  bash scripts/full-pipeline.sh"
echo ""
echo "Environment variables saved to: .env.floci"
echo "Source them with: source .env.floci"
echo ""

log_info "Infrastructure deployment complete!"
