#!/bin/bash
set -e

# Pipeline Verification Script
# Checks that all components are properly configured and connected

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Counters
PASSED=0
FAILED=0
WARNINGS=0

# Functions
log_pass() {
  echo -e "${GREEN}✓${NC} $1"
  ((PASSED++))
}

log_fail() {
  echo -e "${RED}✗${NC} $1"
  ((FAILED++))
}

log_warn() {
  echo -e "${YELLOW}⚠${NC} $1"
  ((WARNINGS++))
}

log_header() {
  echo ""
  echo -e "${BLUE}═══════════════════════════════════════${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}═══════════════════════════════════════${NC}"
  echo ""
}

# Main execution
log_header "PIPELINE VERIFICATION CHECK"

# Check 1: Floci Status
log_header "1. Floci Service Status"
if curl -s "http://localhost:4566/_localstack/health" | grep -q '"state": "running"'; then
  log_pass "Floci is running on http://localhost:4566"
else
  log_fail "Floci is NOT running - start with: bash scripts/setup-floci.sh"
fi

# Check 2: Lambda Code Files
log_header "2. Lambda Function Files"
for lambda in booking events history ticket-generator; do
  if [ -f "$PROJECT_ROOT/backend/$lambda-lambda/index.js" ]; then
    log_pass "Lambda function found: $lambda-lambda/index.js"
  else
    log_fail "Lambda function missing: $lambda-lambda/index.js"
  fi
done

# Check 3: Shared AWS Clients
log_header "3. Shared AWS Client Configuration"
if grep -q "isFlocal" "$PROJECT_ROOT/backend/shared/aws-clients.js"; then
  log_pass "aws-clients.js exports isFlocal correctly"
else
  log_fail "aws-clients.js export bug detected"
fi

if grep -q "endpoint: endpoint" "$PROJECT_ROOT/backend/shared/aws-clients.js"; then
  log_pass "aws-clients.js configures Floci endpoint"
else
  log_fail "aws-clients.js missing endpoint configuration"
fi

# Check 4: Lambda Environment Variables
log_header "4. Lambda Environment Variables in Terraform"
for table in BOOKINGS_TABLE EVENTS_TABLE; do
  if grep -q "$table" "$PROJECT_ROOT/terraform/lambda.tf"; then
    log_pass "Terraform passes $table to Lambda functions"
  else
    log_fail "Terraform missing $table configuration"
  fi
done

if grep -q "BOOKING_QUEUE_URL" "$PROJECT_ROOT/terraform/lambda.tf"; then
  log_pass "Terraform passes BOOKING_QUEUE_URL to booking Lambda"
else
  log_fail "Terraform missing BOOKING_QUEUE_URL"
fi

if grep -q "TICKETS_BUCKET" "$PROJECT_ROOT/terraform/lambda.tf"; then
  log_pass "Terraform passes TICKETS_BUCKET to ticket-generator Lambda"
else
  log_fail "Terraform missing TICKETS_BUCKET"
fi

# Check 5: API Gateway CORS
log_header "5. API Gateway CORS Configuration"
if grep -q "Access-Control-Allow-Origin" "$PROJECT_ROOT/terraform/api_gateway.tf"; then
  log_pass "API Gateway has CORS headers configured"
else
  log_fail "API Gateway missing CORS headers"
fi

if grep -q "OPTIONS" "$PROJECT_ROOT/terraform/api_gateway.tf"; then
  log_pass "API Gateway has OPTIONS methods configured"
else
  log_fail "API Gateway missing OPTIONS methods"
fi

# Check 6: Terraform Files
log_header "6. Terraform Infrastructure Files"
required_files=(
  "main.tf"
  "variables.tf"
  "lambda.tf"
  "dynamodb.tf"
  "sqs.tf"
  "s3.tf"
  "iam.tf"
  "api_gateway.tf"
  "cognito.tf"
)

for file in "${required_files[@]}"; do
  if [ -f "$PROJECT_ROOT/terraform/$file" ]; then
    log_pass "Terraform file found: $file"
  else
    log_fail "Terraform file missing: $file"
  fi
done

# Check 7: Deployment Scripts
log_header "7. Deployment Scripts"
scripts=(
  "setup-floci.sh"
  "deploy-terraform.sh"
  "deploy-infrastructure.sh"
  "seed-data.sh"
  "build-frontend.sh"
  "deploy-frontend.sh"
  "full-pipeline.sh"
  "verify-pipeline.sh"
)

for script in "${scripts[@]}"; do
  if [ -f "$PROJECT_ROOT/scripts/$script" ]; then
    if [ -x "$PROJECT_ROOT/scripts/$script" ]; then
      log_pass "Deployment script found and executable: $script"
    else
      log_warn "Deployment script found but not executable: $script"
      # Make it executable
      chmod +x "$PROJECT_ROOT/scripts/$script"
      log_pass "Made script executable: $script"
    fi
  else
    log_fail "Deployment script missing: $script"
  fi
done

# Check 8: Frontend Configuration
log_header "8. Frontend Configuration"
if [ -f "$PROJECT_ROOT/frontend/.env" ]; then
  log_pass "Frontend .env file exists"
  if grep -q "REACT_APP_API_ENDPOINT" "$PROJECT_ROOT/frontend/.env"; then
    log_pass "Frontend has REACT_APP_API_ENDPOINT configured"
  else
    log_fail "Frontend missing REACT_APP_API_ENDPOINT"
  fi
else
  log_warn "Frontend .env file not found - will be generated by deployment"
fi

# Check 9: Documentation
log_header "9. Documentation"
if [ -f "$PROJECT_ROOT/PIPELINE_AUDIT_REPORT.md" ]; then
  log_pass "Pipeline audit report exists"
else
  log_fail "Pipeline audit report missing"
fi

# Check 10: Git Ignore
log_header "10. Credential Security"
if grep -q "\.env" "$PROJECT_ROOT/.gitignore"; then
  log_pass ".env files are ignored in git"
else
  log_fail ".env files are NOT ignored in git - SECURITY ISSUE"
fi

if grep -q "credentials" "$PROJECT_ROOT/.gitignore"; then
  log_pass "AWS credentials are ignored in git"
else
  log_warn "AWS credentials directory not explicitly ignored"
fi

# Summary
log_header "VERIFICATION SUMMARY"
echo "Checks Passed:  ${GREEN}$PASSED${NC}"
echo "Checks Failed:  ${RED}$FAILED${NC}"
echo "Warnings:       ${YELLOW}$WARNINGS${NC}"
echo ""

if [ $FAILED -eq 0 ]; then
  echo -e "${GREEN}Pipeline is READY for deployment!${NC}"
  echo ""
  echo "Next steps:"
  echo "  1. bash scripts/setup-floci.sh       # Start Floci"
  echo "  2. bash scripts/deploy-terraform.sh  # Deploy infrastructure"
  echo "  3. bash scripts/full-pipeline.sh     # Run complete deployment"
  echo ""
  exit 0
else
  echo -e "${RED}Pipeline has $FAILED critical issue(s) that need fixing.${NC}"
  echo ""
  echo "See the checks above for details."
  exit 1
fi
